# Generated by Django 5.0.3 on 2024-03-26 07:57

import functools

from django.db import migrations, models

import apps.common.services


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrainingSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=functools.partial(
                            apps.common.services.upload_file_handler_path,
                            *("images/training",),
                            **{}
                        ),
                        verbose_name="image",
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "training data"),
                            (1, "data for testing intermediate learning"),
                            (2, "data to verify the final result"),
                        ],
                        default=0,
                        verbose_name="type",
                    ),
                ),
                ("correct_value", models.FloatField(verbose_name="correct value")),
            ],
        ),
    ]
