# Generated by Django 5.0.3 on 2024-03-28 13:46

import functools

from django.db import migrations, models

import apps.common.services


class Migration(migrations.Migration):

    dependencies = [
        ("number_reading", "0002_trainingset_correct_value_categorical_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingset",
            name="image_resized",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=functools.partial(
                    apps.common.services.upload_file_handler_path,
                    *("images/training_resized",),
                    **{}
                ),
                verbose_name="image resized",
            ),
        ),
    ]
