# Generated by Django 5.0.4 on 2024-05-22 12:29

import apps.common.services
import django.db.models.deletion
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NeuralModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NeuralVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(verbose_name="version"),
                ),
                ("changes", models.TextField(verbose_name="changes")),
                (
                    "model",
                    models.FileField(
                        upload_to=functools.partial(
                            apps.common.services.upload_file_handler_path,
                            *("neural_net/models",),
                            **{}
                        )
                    ),
                ),
                ("recognition_rate", models.JSONField()),
                (
                    "neural_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="neural_net.neuralmodel",
                        verbose_name="neural_model",
                    ),
                ),
            ],
        ),
    ]
