# Generated by Django 5.0.4 on 2024-05-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("neural_net", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="neuralversion",
            old_name="recognition_rate",
            new_name="rate",
        ),
    ]
