# Generated by Django 5.0.4 on 2024-05-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "neural_net",
            "0003_remove_neuralversion_rate_neuralversion_recognition",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="neuralversion",
            old_name="recognition",
            new_name="stats",
        ),
    ]
