# Generated by Django 5.0.4 on 2024-05-14 06:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="correct_value",
            field=models.FloatField(verbose_name="correct value"),
        ),
        migrations.AlterField(
            model_name="trainingsetaugmentation",
            name="correct_value",
            field=models.FloatField(verbose_name="correct value"),
        ),
        migrations.AlterField(
            model_name="trainingsetaugmentation",
            name="training_element_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.IntegerField(), size=None
                ),
                size=None,
                verbose_name="correct value categorical",
            ),
        ),
    ]
