# Generated by Django 5.0.4 on 2024-05-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_alter_training_correct_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingelement",
            name="number_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "start"), (1, "middle"), (2, "end")],
                verbose_name="part",
            ),
        ),
    ]
