# Generated by Django 5.0.4 on 2024-05-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_alter_trainingelement_number_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TrainingSetAugmentation",
            new_name="TrainingAugmentation",
        ),
    ]
