# Generated by Django 5.0.4 on 2024-05-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data",
            "0004_rename_trainingsetaugmentation_trainingaugmentation",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="trainingelement",
            old_name="type",
            new_name="meter_type",
        ),
        migrations.AddField(
            model_name="trainingaugmentation",
            name="meter_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "mercury 201")],
                default=1,
                verbose_name="type",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trainingaugmentation",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "teaching data"),
                    (1, "testing data"),
                    (2, "validation data"),
                ],
                default=0,
                verbose_name="type",
            ),
        ),
    ]
