# Generated by Django 5.0.4 on 2024-05-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data",
            "0005_rename_type_trainingelement_meter_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingaugmentation",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "teaching data")],
                default=0,
                verbose_name="type",
            ),
        ),
    ]
